# Generated by Django 5.1.2 on 2024-11-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('TransactionType', models.CharField(max_length=50)),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('DateModified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30, unique=True)),
                ('CurrentBalance', models.CharField(max_length=50)),
                ('FormerBalance', models.CharField(max_length=50)),
                ('ModifiedBy', models.CharField(max_length=30)),
                ('DateModified', models.DateTimeField()),
            ],
        ),
    ]
